import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Icon } from './icons.mjs';
import { edgeDashPattern, edgeAppearanceKey } from 'file:///home/fzg/PycharmProjects/ArchCanvas/ArchCanvas_Model_Architecture_Studio/studio/src/core/edgePresentation.ts';
const ROLE_LABELS = { data: '数据流', residual: '残差', memory: 'Memory', mask: 'Mask' };
/** Screen-space chrome: never contributes geometry or intercepts canvas gestures. */
export function FloatingLegend({ scene, onEdit }) {
    const [collapsed, setCollapsed] = useState(false);
    const variants = [...new Map(scene.edges.map(edge => [JSON.stringify([edge.role, edgeAppearanceKey(edge)]), edge])).values()];
    return _jsxs("aside", { className: `floating-legend ${collapsed ? 'collapsed' : ''}`, "aria-label": "\u60AC\u6D6E\u56FE\u4F8B", onPointerDown: event => event.stopPropagation(), onDoubleClick: event => event.stopPropagation(), onWheel: event => event.stopPropagation(), children: [_jsxs("button", { className: "legend-toggle", "aria-expanded": !collapsed, "aria-label": collapsed ? '展开悬浮图例' : '收起悬浮图例', onClick: () => setCollapsed(value => !value), children: [_jsx(Icon, { name: "layers", size: 14 }), _jsx("b", { children: "\u56FE\u4F8B" }), _jsx("span", { children: collapsed ? '‹' : '›' })] }), !collapsed && _jsxs("div", { className: "floating-legend-content", children: [_jsx("div", { className: "floating-node-legend", children: scene.legend.map(item => _jsxs("div", { "data-floating-legend-id": item.id, children: [_jsx("i", { style: { background: item.color }, "data-glyph": item.glyph, children: item.glyph === 'add' ? '+' : item.glyph === 'attention' ? '≋' : item.glyph === 'tensor' ? '▦' : '▯' }), _jsx("span", { children: item.label })] }, item.id)) }), !!variants.length && _jsx("div", { className: "floating-edge-legend", children: variants.map((edge, index) => _jsxs("div", { children: [_jsxs("svg", { width: "38", height: "14", "aria-hidden": "true", children: [_jsx("path", { d: "M 1 7 H 32", fill: "none", stroke: edge.stroke, strokeWidth: Math.min(4, edge.width), strokeDasharray: edgeDashPattern(edge)?.join(' ') }), _jsx("path", { d: "M 28 4 L 33 7 L 28 10", fill: "none", stroke: edge.stroke })] }), _jsx("span", { children: ROLE_LABELS[edge.role] })] }, `${edge.role}-${index}`)) }), onEdit && _jsx("button", { className: "legend-edit", onClick: onEdit, children: "\u7F16\u8F91\u56FE\u4F8B" })] })] });
}
