"""Retrospective declaration and one immutable raw-file inventory."""
import hashlib
import json
from pathlib import Path
from datetime import datetime, timezone

ROOT=Path(__file__).resolve().parents[3]
WORK=ROOT/'docs/evidence/m4-authoring-interaction-work'
RAW=WORK/'browser-attempt-1'
def bind(p):
    b=p.read_bytes();return dict(path=str(p.relative_to(ROOT)),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
actions=[
 dict(case='new-four-chain', action='Actual empty draft; click Input/Linear/GELU/Output palette cards; public inspector sets x50 and y70/224/378/532, Linear out_features8. No state injection.', expected='Input[1,16] -> Linear16→8 -> GELU -> Output; 4 nodes, 3 edges.'),
 dict(case='label-first',action='Native label-center clicks Input output (677.5602,211.5583) then Linear input (574.8432,335.9145)',before='blank-four-before-connections',pending='label-first-pending',after='label-first-connected',expected='one Input→Linear edge; only their component changes to vertical'),
 dict(case='circle-drag-second',action='Native circle-to-circle drag at public observed Linear output and GELU input centers',before='label-first-connected',after='circle-drag-second-connected',expected='second edge Linear→GELU'),
 dict(case='keyboard-third',action='Enter GELU output, Space Output input using public role buttons',pending='keyboard-third-pending',after='keyboard-third-connected',expected='third edge GELU→Output; vertical routes literal M138170 V224, M138324 V378, M138478 V532'),
 dict(case='duplicate-history-save',action='Repeat third keyboard connection rejected; undo removes third; redo restores it; save then reopen',observations=['duplicate-rejected','undo-third','redo-third','vertical-save-settled','vertical-reopened'],expected='no duplicate binding; edge count3→2→3; saved identities/coordinates retained'),
 dict(case='arrange-and-undo',action='Actual 按连接排版 button makes horizontal rank; undo restores vertical coordinates',observations=['arrange-horizontal','arrange-undone-vertical'],expected='current Arrange is horizontal, not the origin of the manually positioned vertical draft'),
 dict(case='node-four-directions',action='Select Linear title; native Right, Left, Up, Down each16. Extra Left50→34 and undo→50 captured separately.',observations=['linear-selected','node-right16','node-left16','node-up16','node-down16','node-left16-supplement-settled','node-left16-supplement-undone'],expected='Linear (50,224)→(66,224)→(50,224)→(50,208)→(50,224); left compares adjacent right record, not only initial baseline'),
 dict(case='camera-four-directions',action='Native pan right40, left40, up40. Initial down interrupted by 30s tool timeout; partial15 retained. Escape canceled active pan to up camera132.018; single down retry (820,370)→(820,410) restored172.018.',observations=['pan-start','pan-right40','pan-left40','pan-up40','pan-timeout-recovery','pan-cancel-settled','pan-down-retry40'],expected='camera only; graph unchanged; timeout attempt not passed; no general held-pointer cancellation certification'),
 dict(case='four-chain-lifecycle',action='Fit, save/reopen revision2, generate visible source, open fresh managed copy, save rev0, later reload then SVG export180mm',observations=['vertical-saved-final','vertical-final-reopened-before','vertical-generated','managed-new-saved-before','managed-new-reopened','managed-export-settled'],expected='new source306378c82c52 and IR704b0c13; actual export a6ea97deb11a440fbc9aee3aacf1d340; no model execution'),
 dict(case='pending-cancel',action='At100% native Enter Input output then Escape',observations=['vertical-100-pending-before','vertical-100-pending-after','vertical-100-canceled-v2'],expected='pressedtrue→false; postEscape footer retains pending notice; pending JPEG/footer discrepancy is unproven presentation, not a pass'),
 dict(case='merge-authoring',action='Actual blank: InputA(50,80), InputB(50,250), Add(350,160), Concat(620,160), Output(890,160); all via palette/inspector.',expected='Add.left=InputA, Add.right=InputB, Concat.a=Add, Concat.b=InputA fanout, Output.input=Concat; declared output[1,32].'),
 dict(case='merge-native-inputs',action='Group-center InputA(374.4683,335.5972) then Add.left(483.5833,389.3842); circle drag InputB(386.1852,459.1620)→Add.right(476.3148,398.1065); label-center Addout(585.4773,393.4259)→Concat.a(682.9980,389.0648); keyboard InputA→Concat.b and Concat→Output.',observations=['merge-add-left-pending','merge-add-left-connected','merge-add-right-connected','merge-concat-a-pending','merge-concat-a-connected','merge-concat-b-fanout-connected','merge-complete-fit-before','merge-saved-settled','merge-generated'],expected='five distinct edges, ordered input ports and same-source fanout, no node move caused by connection'),
 dict(case='starting-graphs',action='Click residualMLP6/6 then save; click MLP5/4 then save/static generate; new blank native CNN card(102,524)→canvas(600,300), eight nodes/seven edges, save/static generate.',observations=['residual-preset-native-fit','residual-saved-settled','mlp-saved-settled','mlp-generated','cnn-drag-before-empty','cnn-saved-settled','cnn-generated'],expected='17 visible basic kinds including SiLU; 3 transparent editable graphs. Residual was not generated this round; no per-module/runtime/human certification')
]
single={'managed-reopened':'managed-reopened','cnn-reopened-fit':'cnn-reopened-fit','arrange-horizontal':'arrange-horizontal','vertical-four-connected':'keyboard-third-connected'}
bracket=['vertical-final-reopened','vertical-100-pending','residual-preset-fit','merge-complete-fit','merge-complete-100','mlp-preset-native-fit','cnn-preset-native-drag-fit','managed-new-saved','managed-new-final','managed-new-clear-supplement']
screens=[]
for p in sorted(RAW.glob('*.jpg')):
    n=p.stem
    screens.append(dict(image=p.name,observations=[n+'-before',n+'-after'] if n in bracket else [single[n]],mapping='Retrospective capture mapping, not proof all raster pixels match bracketed DOM. Pixel reviewer checks each image; stale/modal/misnamed frames remain failures.'))
x=dict(schemaVersion=1,generatedAt=datetime.now(timezone.utc).isoformat(),scope='Bounded native root-operated UI trials with three independent AI reviewer roles; zero humans.',browser='2',tab='60',url='http://127.0.0.1:40875/',actionDeclaration='Retrospective from actual tool calls and saved observations; not synchronous OS telemetry.',rawClosed=True,actions=actions,screenshots=screens,observationFailures=['After kernel reset, early capture helper used old closure: derived port.node and edge.path are null, while svg is complete. Kept unchanged; v2 inline reader fixes later observations, not prior raw.','pan down first attempt timed out during gesture. Partial camera15 and cancellation/new retry retained.','Screenshot file names and DOM brackets do not establish raster equivalence or exact visible zoom; independent reviewer retains stale fit/100/modal/footer discrepancies.'],assetsScope='Observed pageAssets URLs and read-only current HTTP JS/CSS bytes equal final build; no direct browser-cache-memory proof.',actualArtifacts=bind(WORK/'actual-artifacts-attempt-1/manifest.json'),records=[bind(p) for p in sorted(RAW.iterdir()) if p.is_file()])
p=WORK/'browser-final-manifest-attempt-1.json';assert not p.exists();p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print(json.dumps(dict(rawFiles=len(x['records']),screenshots=len(screens),manifest=bind(p)),ensure_ascii=False))
