"""Bind current receipts without promoting AI or historical gates."""
from pathlib import Path
import hashlib
import json
from datetime import datetime, timezone

ROOT=Path(__file__).resolve().parents[3]
WORK=Path(__file__).resolve().parent
path=ROOT/'docs/evidence/m4-human-review-handoff-status.json'
old=json.loads(path.read_text());assert old['schemaVersion']==11
def bind(p):
    if isinstance(p,str):p=ROOT/p
    b=p.read_bytes();return dict(path=str(p.relative_to(ROOT)),bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
def wp(p):return str((WORK/p).relative_to(ROOT))
pixel=wp('visual-review-attempt-1/final-review-receipt.json')
assert (ROOT/pixel).is_file()
prior_manifest=json.loads((WORK/'before-current-doc-update-attempt-1/manifest.json').read_text())
prior_status=next(r['copy'] for r in prior_manifest['records'] if r['source']['path']==str(path.relative_to(ROOT)))
new={k:v for k,v in old.items() if k not in ('collapseContinuity','authoring','tests','previousStatus','evidenceRefs','openItems','scope','preservedFailures')}
new.update(schemaVersion=12,generatedAt=datetime.now(timezone.utc).isoformat(),scope='Current per-network draft flow, port hit/keyboard interaction, aliased Output caption, bounded native authoring/lifecycle/artifact and AI pixels. Native geometry checks pass; merge route aesthetics do not pass. No human, physical publication, global aesthetics, full39 or presented-performance certification.',productionBuild='index-ye7sAyyI.js',productionJsSha256='3e6fd1fea0cb5b3c286758e1bc6216e21e87f59ce0479e704faae80c5ed63164',productionCss='index-C769d2rm.css',productionCssSha256='4bd0d31a6e028cfa96e90eef56bdeb08b0cea5307e666033e55a23200ebf2646',productionIndexSha256='7abc79b1c61e3ff83ba6c4e44c14b64247c926c282b26fd2ae4368f5218a4c2f')
new['tests']=dict(studio=dict(passed=264,failed=0,skipped=0,exitCode=0,receipt=wp('checks/suite-attempt-2/receipt.json'),sourceBeforeAfterExact=True),focusedSeparateRun=dict(passed=28,failed=0,skipped=0,exitCode=0,receipt=wp('checks/target-attempt-2/receipt.json')),strictTypescriptExitCode=0,buildExitCode=0,buildReceipt=wp('checks/build-attempt-2/receipt.json'),suiteCountsCombined=False,pythonFullSuiteRerunThisRound=False,currentFullStandaloneReleaseCertified=False,independentCheckAudit=wp('acceptance/final-check-readback-attempt-1/report.json'),independentCheckInputCount=209)
new['priorCollapseStage']=dict(build=old['productionBuild'],scope='Frozen prior BK evidence; retained implementation unchanged, not a current full browser matrix.',tests=old['tests'],native=old['collapseContinuity'],seal=bind('docs/evidence/m4-collapse-continuity-verification-sealed.json'),mutablePathResolution=wp('before-implementation-attempt-1/manifest.json'))
new['authoring']=dict(baseModules=17,transparentStartingGraphs=3,catalogIncludes='SiLU, not Softmax; Attention/LSTM unsupported',fourNodeChain='Input→Linear(16→8)→GELU→Output',nodes=4,edges=3,chainInitiallyCreatedOn=new['productionBuild'],nativeConnectionModes=['label-center click','circle drag','Enter/Space'],verticalAlignedRouteBends=[0,0,0],arrangeFlow='horizontal rank',savedDraftRevision=27,savedDraftStorageRevision=2,managedSavedRevision=0,managedStorageRevision=1,managedReopened=True,exportUuid='a6ea97deb11a440fbc9aee3aacf1d340',exportWidthMm=180,exportHeightMm=196.6386554621849,mergeNodes=5,mergeEdges=5,mergeExpected='Add.left=A; Add.right=B; Concat.a=Add; Concat.b=A; Output=Concat',mergeStaticGeneration=True,mlpPresetNativeClickNodes=5,mlpPresetEdges=4,residualPresetNativeClickNodes=6,residualPresetEdges=6,residualGeneratedThisRound=False,cnnNativeDragNodes=8,cnnNativeDragEdges=7,cnnStaticGenerationVerified=True,cnnManagedOpenVerified=False,independentArtifactAudit=wp('authoring-artifact-audit-attempt-1/attempt-2/receipt.json'),independentArtifactCasesPassed=6,independentArtifactInputs=33,newPerModuleBrowserCertification=False,newRuntimeCertification=False,humanNoviceCertification=False,remainingIssues=['different-producer merge crossing(614,220)','CNN long two-row return','small multi-input targets at fit scale','axis-threshold port-side changes without hysteresis','estimated label hit width does not prove arbitrary labels','Escape clears pending but leaves old pending footer','some screenshots mismatch DOM or file names/zoom/modal state'])
new['authoringInteraction']=dict(flowContractCases=11,baselineOriginalCases=10,baselineOriginalPassed=4,intermediateGlobalCases=11,intermediateGlobalPassed=10,perComponentFinalPassed=11,captionIndependentCases=6,captionAndExistingPathSeparatePassed=9,nativeAudit=wp('acceptance/native-audit-attempt-1/report.json'),nativeScopedChecksPassed=46,rawFiles=165,rawScreenshots=14,authoringSnapshots=59,endpointPairs=195,visiblePublicCenters=1424,visibleCenterIdentitiesMatched=1424,failedDerivedObserverSnapshots=11,cardInteriorPenetrations=0,strictCrossingFree=False,strictCrossingPoints=[[614,220]],repeatCrossingObservations=6,nodeMoves=['right16','left16','up16','down16'],cameraMoves=['right40','left40','up40','down40 retry'],panInitialDownTimedOut=True,panRetryRestoredCamera=True,pendingPixelFooterCertified=False,merge100PercentPixelsCertified=False,fullAestheticsCertified=False,pixelReceipt=pixel,sourceBoundaryReview=wp('acceptance/source-review-attempt-1/report.json'),actualArtifactManifest=wp('actual-artifacts-attempt-1/manifest.json'),browserManifest=wp('browser-final-manifest-attempt-1.json'),observedCurrentHttpAssetBytesMatchBuild=True,browserCacheBytesIndependentlyRead=False)
new['aiReview']['roles']=['mono_acceptance: independent flow/source contract, tests/build and native endpoint/hit/history audit','mono_pixels: actual screenshot and public geometry AI review with failed frames retained','performance_controls: independent generated AST/source/document/export artifact audit']
new['aiReview']['reviewerRoleCount']=3
new['previousStatus']=prior_status
new['openItems']=['current Studio matched A/B performance, three-replicate matrix and actual presentation','general held-pointer cancellation','actual physical85/180mm human publication review','3–5 actual researcher tasks; current build research preparation pending','Transformer crossings/overlaps, expanded header detours and deep tall pages','width4 monochrome role dash gaps','authoring merge crossing(614,220), long CNN return and small fit port targets','axis-threshold direction changes, arbitrary-label hit width and stale pending notice','screenshot/DOM presentation mismatch remains unproven','expansion screen anchor requires matched immediate-before camera evidence','no per-module runtime/training or current full39/full standalone release certification']
new['preservedFailures']=old['preservedFailures']+['independent baseline Node isolation recorder failure','global-flow mixed-component failure and intermediate27/263 build','after-reset observer null derived endpoint identities/paths','initial down-pan30s tool timeout and partial15px/cancel/retry','misnamed fit/100 and stale edge-count/modal/pending-footer raster','artifact reviewer overstrict physical root precision corrected to5-decimal independent encoding','sandbox first HTTP resource socket rejection before authorized readback']
refs=['docs/m4-authoring-interaction.md',wp('checks/target-attempt-2/receipt.json'),wp('checks/suite-attempt-2/receipt.json'),wp('checks/build-attempt-2/receipt.json'),wp('acceptance/current-target-attempt-3/receipt.json'),wp('acceptance/source-review-attempt-1/report.json'),wp('acceptance/final-check-readback-attempt-1/report.json'),wp('acceptance/native-audit-attempt-1/report.json'),wp('output-caption/attempt-1/final-receipt.json'),wp('authoring-artifact-audit-attempt-1/attempt-2/receipt.json'),wp('authoring-artifact-audit-attempt-1/seal.json'),pixel,wp('browser-final-manifest-attempt-1.json'),wp('actual-artifacts-attempt-1/manifest.json'),wp('before-implementation-attempt-1/manifest.json'),wp('before-current-doc-update-attempt-1/manifest.json'),'docs/evidence/m4-collapse-continuity-verification-sealed.json','docs/evidence/m4-monochrome-role-verification-sealed.json','docs/evidence/m4-monochrome-width-pixel-supplement-attempt-1/receipt.json','docs/evidence/m4-performance-controls-work/analysis-attempt-3/receipt.json','studio/src/authoring.ts','studio/src/AuthoringStudio.tsx','studio/src/AuthoringStudio.css','studio/src/draftPortPresentation.ts','studio/src/core/scene.ts','studio/src/core/document.ts','studio/dist/index.html','studio/dist/assets/index-ye7sAyyI.js','studio/dist/assets/index-C769d2rm.css']
new['evidenceRefs']=[bind(r) for r in refs]
path.write_text(json.dumps(new,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(status=bind(path),refs=len(refs)),ensure_ascii=False))
