import test from 'node:test';
import assert from 'node:assert/strict';
import { joinNativeTrials, summarizeNativeTrials } from '../src/nativePerformance.ts';
import type { NativeScene, NativeTrial } from '../src/nativePerformance.ts';
import type { EventTimingSample } from '../src/perf.ts';
// @ts-expect-error The independent Node receipt verifier has no declarations.
import { validateNativePerformance } from '../../scripts/validate_native_performance.mjs';

// Authored timing/identity examples, not browser measurements. The expected
// pairs are stated explicitly; no expected receipt is generated by the join.
function trial(at: number, targetId = 'A', eventName: NativeTrial['eventName'] = 'click', trusted = true): NativeTrial {
  const anchor = { canvas: { x: 10, y: 20 }, screen: { x: 30, y: 40 } };
  const before: NativeScene = { documentId: 'matching-oracle', revision: 0, sourceDigest: 'a'.repeat(64), irDigest: 'b'.repeat(64),
    visibleIds: [targetId], expandedIds: [], pinnedIds: [], anchors: { [targetId]: anchor } };
  const after: NativeScene = { ...structuredClone(before), revision: 1, visibleIds: [targetId, `${targetId}.child`], expandedIds: [targetId] };
  return { eventName, eventAt: at, capturedAt: at + 1, trusted, targetId, operation: 'expand', before, after, error: null };
}

function event(at: number, targetCanonicalNodeId: string | null = 'A', durationMs = 32, name = 'click'): EventTimingSample {
  return { name, startAt: at, targetCanonicalNodeId, interactionId: 17,
    processingStart: at + 1, processingEnd: at + 2, durationMs };
}

function expectedReceipt(trials: NativeTrial[], events: EventTimingSample[], pairs: (EventTimingSample | null)[], p95: number | null) {
  assert.equal(trials.length, pairs.length);
  return { schemaVersion: 1, protocol: 'archcanvas-native-performance/1',
    measurement: { latency: 'native-event-timing-to-next-paint', geometryBoundary: 'two-animation-frames-after-input', durationThresholdMs: 16, durationQuantizationMs: 8 },
    bindingAtStart: trials[0].before,
    trials: trials.map((item, index) => ({ ...structuredClone(item), bindingValid: true, targetChanged: true,
      nativeEventTiming: pairs[index], nativeInputToNextPaintMs: pairs[index]?.durationMs ?? null,
      anchorScreenDisplacementPx: 0, pins: [] })),
    summary: { capturedTrials: trials.length, validSceneTrials: trials.length, matchedNativeTrials: pairs.filter(Boolean).length,
      nativeInputToNextPaintP95Ms: p95, anchorScreenMaxPx: 0, measuredPinCount: 0, pinCanvasMaxPx: null,
      unmeasuredPinCount: 0, certification: 'pending-fixed-environment-and-review' },
    snapshot: { eventTiming: events },
    frames: { frameCount: 0, firstFrameAt: null, lastFrameAt: null, intervals: [], intervalP95Ms: null, fps: null } };
}

function check(trials: NativeTrial[], events: EventTimingSample[], pairs: (EventTimingSample | null)[], p95: number | null) {
  const joined = joinNativeTrials(trials, events);
  assert.deepEqual(joined.map(item => item.nativeEventTiming), pairs);
  assert.deepEqual(joined.map(item => item.nativeInputToNextPaintMs), pairs.map(item => item?.durationMs ?? null));
  assert.equal(summarizeNativeTrials(joined).nativeInputToNextPaintP95Ms, p95);
  const receipt = expectedReceipt(trials, events, pairs, p95);
  assert.equal(validateNativePerformance(receipt).matchedNativeTrials, pairs.filter(Boolean).length);
  return receipt;
}

test('two trusted trials competing for one raw event both remain unmatched', () => {
  const trials = [trial(100), trial(104)], native = event(102);
  const receipt = check(trials, [native], [null, null], null);
  assert.deepEqual(joinNativeTrials([...trials].reverse(), [native]).map(item => item.nativeEventTiming), [null, null]);
  // A forged first-come claim is rejected even if its summary is changed too.
  receipt.trials[0].nativeEventTiming = native;
  receipt.trials[0].nativeInputToNextPaintMs = 32;
  receipt.summary.matchedNativeTrials = 1;
  receipt.summary.nativeInputToNextPaintP95Ms = 32;
  assert.throws(() => validateNativePerformance(receipt), /missing, ambiguous or incorrectly matched/);
});

test('a fully overlapping 2 by 2 candidate graph has no unique pair under either array order', () => {
  const trials = [trial(100), trial(104)], events = [event(100), event(108, 'A', 40)];
  check(trials, events, [null, null], null);
  for (const orderedTrials of [trials, [...trials].reverse()]) {
    for (const orderedEvents of [events, [...events].reverse()]) {
      assert.deepEqual(joinNativeTrials(orderedTrials, orderedEvents).map(item => item.nativeEventTiming), [null, null]);
    }
  }
  check(trials, [...events].reverse(), [null, null], null);
});

test('a one-candidate trial cannot steal an event from a competing two-candidate trial', () => {
  // A@100 can see only e@108; B@112 can see e@108 and e@120.
  // The raw event e@108 has two candidates, so A is not uniquely paired.
  const trials = [trial(100), trial(112)], events = [event(108), event(120, 'A', 40)];
  check(trials, events, [null, null], null);
  for (const orderedTrials of [trials, [...trials].reverse()]) {
    for (const orderedEvents of [events, [...events].reverse()]) {
      assert.deepEqual(joinNativeTrials(orderedTrials, orderedEvents).map(item => item.nativeEventTiming), [null, null]);
    }
  }
  const forged = expectedReceipt(trials, events, events, 40);
  assert.throws(() => validateNativePerformance(forged), /missing, ambiguous or incorrectly matched/);
});

test('the matching window includes both exact 8 ms endpoints and excludes points beyond them', () => {
  for (const at of [92, 108]) {
    const native = event(at);
    check([trial(100)], [native], [native], 32);
  }
  for (const at of [91.999999, 108.000001]) {
    check([trial(100)], [event(at)], [null], null);
  }
  // A boundary entry shared by both endpoints is still ambiguous.
  check([trial(100), trial(116)], [event(108)], [null, null], null);
});

test('different target identities separate otherwise identical timing windows', () => {
  const trials = [trial(100, 'A'), trial(100, 'B')], events = [event(100, 'A'), event(100, 'B', 40)];
  check(trials, events, events, 40);
  check(trials, [...events].reverse(), events, 40);
  assert.deepEqual(joinNativeTrials([...trials].reverse(), events).map(item => item.nativeEventTiming), [...events].reverse());
  check([trial(100)], [event(100, 'B'), event(100, null)], [null], null);
});

test('different event names separate otherwise identical target and timing windows', () => {
  const trials = [trial(100), trial(100, 'A', 'pointerdown')], events = [event(100), event(100, 'A', 40, 'pointerdown')];
  check(trials, events, events, 40);
  check(trials, [...events].reverse(), events, 40);
  assert.deepEqual(joinNativeTrials([...trials].reverse(), events).map(item => item.nativeEventTiming), [...events].reverse());
});

test('an untrusted competitor does not consume or make a trusted event ambiguous', () => {
  const trials = [trial(100), trial(104, 'A', 'click', false)], native = event(102);
  check(trials, [native], [native, null], 32);
  assert.deepEqual(joinNativeTrials([...trials].reverse(), [native]).map(item => item.nativeEventTiming), [null, native]);
});

test('ambiguity in one target component does not erase a separate unique component', () => {
  const trials = [trial(100), trial(104), trial(104, 'B')], events = [event(102), event(104, 'B', 48)];
  check(trials, events, [null, null, events[1]], 48);
  assert.deepEqual(joinNativeTrials([...trials].reverse(), [...events].reverse()).map(item => item.nativeEventTiming), [events[1], null, null]);
});

test('duplicate raw records remain separate candidates and cannot fabricate uniqueness', () => {
  const native = event(100);
  check([trial(100)], [native, structuredClone(native)], [null], null);
  const forged = expectedReceipt([trial(100)], [native, structuredClone(native)], [native], 32);
  assert.throws(() => validateNativePerformance(forged), /missing, ambiguous or incorrectly matched/);
});
