"""Read-only XML review of actual saved browser scene captures."""
from pathlib import Path
import json,hashlib,xml.etree.ElementTree as E
root=Path.cwd();out=root/'docs/evidence/m4-caption-route-current/browser-caption-investigation';browser=root/'docs/evidence/m4-caption-route-current/browser/continuation';records=[]
for name in ['04-divs-100-settled','22-encoder-down-association','23-encoder-undo-restored']:
 path=browser/(name+'.svg');tree=E.fromstring(path.read_bytes());meta=json.loads(next(n.text for n in tree.iter() if n.tag.endswith('metadata')));edge=next(n for n in tree.iter() if n.attrib.get('data-edge-id')=='edge:44');route=next(n.attrib['d'] for n in edge if n.tag.endswith('path'));texts=[n.text for n in edge if n.tag.endswith('text')];guides=[n.attrib for n in tree.iter() if n.attrib.get('data-caption-for-edge')=='edge:44'];encoder=next(n for n in tree.iter() if n.attrib.get('data-node-id')=='repeat:instance:model.Transformer.encoder');front=next(n for n in encoder if n.tag.endswith('rect') and n.get('opacity') is None);decoder=next(n for n in tree.iter() if n.attrib.get('data-node-id')=='call:instance:model.Transformer.decoder');decoderFront=next(n for n in decoder if n.tag.endswith('rect') and n.get('opacity') is None)
 records.append({'name':name,'path':str(path.relative_to(root)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'documentId':meta['documentId'],'revision':meta['revision'],'sourceDigest':meta['sourceDigest'],'irDigest':meta['irDigest'],'sourceFacts':meta['sourceFacts'],'renderedBinding':next(r for r in meta['renderedBindings'] if r['sceneEdgeId']=='edge:44'),'edgePath':route,'edgeTexts':texts,'guides':guides,'encoder':front.attrib,'decoder':decoderFront.attrib})
replay=json.loads((out/'replay.json').read_text());copy=next(r for r in replay['records'] if r['name']=='encoder-dy-24');a,b,c=records
report={'schema':'archcanvas-browser-memory-caption-observation/1','records':records,'exactCanonicalBindingAcrossCaptures':a['renderedBinding']==b['renderedBinding']==c['renderedBinding'],'exactSourceFactsAcrossCaptures':a['sourceFacts']==b['sourceFacts']==c['sourceFacts'],'exactSourceAndIrDigestsAcrossCaptures':all((r['sourceDigest'],r['irDigest'])==(a['sourceDigest'],a['irDigest']) for r in records),'actualMoveReproducedByDetachedCurrentScene':copy['current']['edge']['path']==b['edgePath'] and copy['current']['edge']['label']=='' and not copy['current']['guides'],'baselineAlsoDropsLabel':copy['baseline']['edge']['label']=='','undoRestoresMemoryTextAndGuide':c['edgeTexts']==a['edgeTexts'] and c['guides']==a['guides'],'noCaptionAssociationDiagnosticAfterDrop':not copy['current']['diagnostics']}
(out/'browser-report.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k not in ['records']}))
