#!/usr/bin/env bash
set -euo pipefail
backup="${ARCHCANVAS_PORT_ROUTING_BACKUP:-/tmp/archcanvas-port-routing-before-20261009}"
project="$(cd "$(dirname "$0")/../../.." && pwd)"
if [[ ! -d "$backup" ]]; then echo "Missing backup: $backup" >&2; exit 1; fi
cd "$project"
mkdir -p "$(dirname README.md)"
cp "$backup/README.md" "$project/README.md"
mkdir -p "$(dirname src/archcanvas_authoring/catalog.py)"
cp "$backup/src/archcanvas_authoring/catalog.py" "$project/src/archcanvas_authoring/catalog.py"
mkdir -p "$(dirname src/archcanvas_authoring/custom_modules.py)"
cp "$backup/src/archcanvas_authoring/custom_modules.py" "$project/src/archcanvas_authoring/custom_modules.py"
mkdir -p "$(dirname src/archcanvas_authoring/draft.py)"
cp "$backup/src/archcanvas_authoring/draft.py" "$project/src/archcanvas_authoring/draft.py"
mkdir -p "$(dirname src/archcanvas_authoring/source_import.py)"
cp "$backup/src/archcanvas_authoring/source_import.py" "$project/src/archcanvas_authoring/source_import.py"
mkdir -p "$(dirname src/archcanvas_cli/server.py)"
cp "$backup/src/archcanvas_cli/server.py" "$project/src/archcanvas_cli/server.py"
mkdir -p "$(dirname studio/src/App.tsx)"
cp "$backup/studio/src/App.tsx" "$project/studio/src/App.tsx"
mkdir -p "$(dirname studio/src/AuthoringStudio.tsx)"
cp "$backup/studio/src/AuthoringStudio.tsx" "$project/studio/src/AuthoringStudio.tsx"
mkdir -p "$(dirname studio/src/authoring.ts)"
cp "$backup/studio/src/authoring.ts" "$project/studio/src/authoring.ts"
mkdir -p "$(dirname studio/src/authoringPresets.ts)"
cp "$backup/studio/src/authoringPresets.ts" "$project/studio/src/authoringPresets.ts"
mkdir -p "$(dirname studio/src/core/document.ts)"
cp "$backup/studio/src/core/document.ts" "$project/studio/src/core/document.ts"
rm -f studio/src/core/layerOrdering.ts
mkdir -p "$(dirname studio/src/core/memoryContinuity.ts)"
cp "$backup/studio/src/core/memoryContinuity.ts" "$project/studio/src/core/memoryContinuity.ts"
mkdir -p "$(dirname studio/src/core/orthogonalRouter.ts)"
cp "$backup/studio/src/core/orthogonalRouter.ts" "$project/studio/src/core/orthogonalRouter.ts"
rm -f studio/src/core/portRouting.ts
mkdir -p "$(dirname studio/src/core/scene.ts)"
cp "$backup/studio/src/core/scene.ts" "$project/studio/src/core/scene.ts"
mkdir -p "$(dirname studio/src/core/svg.ts)"
cp "$backup/studio/src/core/svg.ts" "$project/studio/src/core/svg.ts"
mkdir -p "$(dirname studio/src/core/types.ts)"
cp "$backup/studio/src/core/types.ts" "$project/studio/src/core/types.ts"
mkdir -p "$(dirname studio/src/core/validate.ts)"
cp "$backup/studio/src/core/validate.ts" "$project/studio/src/core/validate.ts"
mkdir -p "$(dirname studio/src/customModules.ts)"
cp "$backup/studio/src/customModules.ts" "$project/studio/src/customModules.ts"
mkdir -p "$(dirname studio/src/draftNodeGeometry.ts)"
cp "$backup/studio/src/draftNodeGeometry.ts" "$project/studio/src/draftNodeGeometry.ts"
mkdir -p "$(dirname studio/src/draftPortPresentation.ts)"
cp "$backup/studio/src/draftPortPresentation.ts" "$project/studio/src/draftPortPresentation.ts"
mkdir -p "$(dirname studio/src/draftValidation.ts)"
cp "$backup/studio/src/draftValidation.ts" "$project/studio/src/draftValidation.ts"
mkdir -p "$(dirname studio/src/generatedCanvas.ts)"
cp "$backup/studio/src/generatedCanvas.ts" "$project/studio/src/generatedCanvas.ts"
mkdir -p "$(dirname studio/src/generatedWorkspace.ts)"
cp "$backup/studio/src/generatedWorkspace.ts" "$project/studio/src/generatedWorkspace.ts"
mkdir -p "$(dirname studio/src/sourceDraftFrontier.ts)"
cp "$backup/studio/src/sourceDraftFrontier.ts" "$project/studio/src/sourceDraftFrontier.ts"
mkdir -p "$(dirname studio/tests/authoring-flow-independent.test.ts)"
cp "$backup/studio/tests/authoring-flow-independent.test.ts" "$project/studio/tests/authoring-flow-independent.test.ts"
mkdir -p "$(dirname studio/tests/authoring-interaction-independent.test.ts)"
cp "$backup/studio/tests/authoring-interaction-independent.test.ts" "$project/studio/tests/authoring-interaction-independent.test.ts"
mkdir -p "$(dirname studio/tests/authoring-presets.test.ts)"
cp "$backup/studio/tests/authoring-presets.test.ts" "$project/studio/tests/authoring-presets.test.ts"
mkdir -p "$(dirname studio/tests/camera-viewport-resize-independent.test.ts)"
cp "$backup/studio/tests/camera-viewport-resize-independent.test.ts" "$project/studio/tests/camera-viewport-resize-independent.test.ts"
mkdir -p "$(dirname studio/tests/draft-merge-routing-independent.test.ts)"
cp "$backup/studio/tests/draft-merge-routing-independent.test.ts" "$project/studio/tests/draft-merge-routing-independent.test.ts"
mkdir -p "$(dirname studio/tests/draft-port-geometry-independent.test.ts)"
cp "$backup/studio/tests/draft-port-geometry-independent.test.ts" "$project/studio/tests/draft-port-geometry-independent.test.ts"
mkdir -p "$(dirname studio/tests/editor-workflow-independent.test.ts)"
cp "$backup/studio/tests/editor-workflow-independent.test.ts" "$project/studio/tests/editor-workflow-independent.test.ts"
mkdir -p "$(dirname studio/tests/move-command-independent.test.ts)"
cp "$backup/studio/tests/move-command-independent.test.ts" "$project/studio/tests/move-command-independent.test.ts"
rm -f studio/tests/port-routing.test.ts
mkdir -p "$(dirname studio/tests/source-authoring-compact-ui.test.ts)"
cp "$backup/studio/tests/source-authoring-compact-ui.test.ts" "$project/studio/tests/source-authoring-compact-ui.test.ts"
echo "Restored the files listed in manifest.json from $backup."
