import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { evidenceText, instanceCalls, outputPathText } from 'file:///home/fzg/PycharmProjects/ArchCanvas/ArchCanvas_Model_Architecture_Studio/studio/src/core/nodeFacts.ts';

export function ObjectFacts({ architecture, node, onSelect }) {
    const calls = instanceCalls(architecture, node);
    return _jsxs("section", { className: "property-section object-facts", "aria-label": "\u5BF9\u8C61\u6765\u6E90\u4E8B\u5B9E", children: [_jsxs("h3", { children: ["\u5BF9\u8C61\u6765\u6E90", _jsx("span", { className: "read-only", children: "\u53EA\u8BFB" })] }), node.repeat && _jsxs("p", { className: "field-help", "data-fact": "repeat", children: [node.repeat.count, " \u6B21\u91CD\u590D \u00B7 ", node.repeat.sharing === 'shared' ? '共享实例' : '独立实例'] }), calls.length > 1 && _jsxs(_Fragment, { children: [_jsxs("p", { className: "field-help", "data-fact": "shared-instance", children: ["\u5171\u4EAB\u540C\u4E00\u5B9E\u4F8B \u00B7 ", calls.length, " \u4E2A\u4E0D\u540C\u8C03\u7528"] }), _jsx("ul", { className: "fact-peer-list", children: calls.map((call, index) => _jsx("li", { children: onSelect && call.id !== node.id
                                ? _jsxs("button", { className: "text-button", onClick: () => onSelect(call.id), children: [call.label, " \u00B7 \u8C03\u7528 ", index + 1] })
                                : _jsxs("span", { children: [call.label, " \u00B7 \u8C03\u7528 ", index + 1, call.id === node.id ? '（当前）' : ''] }) }, call.id)) })] }), node.outputPath && _jsxs("p", { className: "field-help", "data-fact": "output-path", children: ["\u8FD4\u56DE\u69FD\u4F4D\uFF1A", _jsx("code", { children: outputPathText(node.outputPath) })] }), _jsx("p", { className: "field-help", "data-fact": "evidence", children: evidenceText(node) }), node.source && _jsxs("p", { className: "field-help", "data-fact": "source", children: [node.source.path, ":", node.source.line, "\u2013", node.source.endLine] }), _jsxs("details", { className: "fact-identities", children: [_jsx("summary", { children: "\u7A33\u5B9A\u8EAB\u4EFD\u4E0E\u539F\u59CB\u8868\u8FBE\u5F0F" }), _jsxs("dl", { className: "parameters", children: [_jsxs("div", { children: [_jsx("dt", { children: "\u5BF9\u8C61" }), _jsx("dd", { children: node.id })] }), node.instanceId && _jsxs("div", { children: [_jsx("dt", { children: "\u5B9E\u4F8B" }), _jsx("dd", { children: node.instanceId })] }), node.callId && _jsxs("div", { children: [_jsx("dt", { children: "\u8C03\u7528" }), _jsx("dd", { children: node.callId })] }), node.source && _jsxs("div", { children: [_jsx("dt", { children: "\u8868\u8FBE\u5F0F" }), _jsx("dd", { children: node.source.expression })] })] })] })] });
}
