#!/usr/bin/env python3
"""Read-only, model-free local Codex Skill discovery probe.

This starts a dedicated stdio app-server, sends only initialize and skills/list,
and terminates that exact process. It does not start a thread/turn, invoke any
model, install any Skill, write a Codex config or use the shared app daemon.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import selectors
import shutil
import subprocess
import time
from pathlib import Path


def encode(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cwd", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--expected-skill", type=Path)
    args = parser.parse_args()
    cwd = args.cwd.resolve(strict=True)
    if args.output.exists():
        raise ValueError("probe output must be new")
    args.output.mkdir(parents=True)
    executable = shutil.which("codex")
    if executable is None:
        raise ValueError("codex is not in PATH")
    version = subprocess.run([executable, "--version"], capture_output=True, text=True, timeout=10)
    command = [executable, "app-server", "--listen", "stdio://", "--disable", "plugins", "--disable", "apps",
               "-c", "analytics.enabled=false", "-c", "mcp_servers={}"]
    # The protocol schema generated by this exact CLI defines these methods.
    requests = [
        {"id": 1, "method": "initialize", "params": {"clientInfo": {"name": "archcanvas-portability-audit", "version": "1"}, "capabilities": {"experimentalApi": False}}},
        {"method": "initialized", "params": {}},
        {"id": 2, "method": "skills/list", "params": {"cwds": [str(cwd)], "forceReload": True}},
    ]
    transcript: list[dict] = []
    stderr: list[str] = []
    started = time.monotonic()
    process = subprocess.Popen(command, cwd=cwd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                               text=True, bufsize=1)
    selector = selectors.DefaultSelector()
    assert process.stdin is not None and process.stdout is not None and process.stderr is not None
    selector.register(process.stdout, selectors.EVENT_READ, "stdout")
    selector.register(process.stderr, selectors.EVENT_READ, "stderr")

    def send(request: dict) -> None:
        transcript.append({"direction": "client", "message": request})
        process.stdin.write(json.dumps(request) + "\n")
        process.stdin.flush()

    terminal = None
    error = None
    try:
        send(requests[0])
        while time.monotonic() - started < 30:
            for key, _mask in selector.select(timeout=0.2):
                line = key.fileobj.readline()
                if not line:
                    selector.unregister(key.fileobj)
                    continue
                if key.data == "stderr":
                    stderr.append(line.rstrip())
                    continue
                try:
                    message = json.loads(line)
                except json.JSONDecodeError:
                    error = "stdout was not JSON-lines protocol"
                    break
                transcript.append({"direction": "server", "message": message})
                if message.get("id") == 1:
                    if "error" in message:
                        error = "initialize rejected"
                        break
                    send(requests[1])
                    send(requests[2])
                if message.get("id") == 2:
                    terminal = message
                    break
            if error is not None or terminal is not None:
                break
            if process.poll() is not None and not selector.get_map():
                error = "app-server exited before skills/list"
                break
        if terminal is None and error is None:
            error = "skills/list did not finish within 30 seconds"
    finally:
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=5)
        selector.close()
    entries = terminal.get("result", {}).get("data", []) if terminal else []
    rows = [row for entry in entries for row in entry.get("skills", []) if row.get("name") == "archcanvas"]
    expected = str(args.expected_skill.resolve(strict=True)) if args.expected_skill else None
    exact = [row for row in rows if Path(row["path"]).resolve() == Path(expected)] if expected else []
    expected_ok = ((not expected and len(rows) == 0) or (expected and len(rows) == 1 and len(exact) == 1))
    receipt = {
        "schema": "archcanvas-codex-discovery-probe/1", "scope": "dedicated-local-app-server-skills-list-only",
        "status": "passed" if terminal and "result" in terminal and expected_ok else "failed",
        "cliExecutable": executable, "cliVersion": version.stdout.strip(), "versionExitCode": version.returncode,
        "cwd": str(cwd), "command": command, "elapsedSeconds": time.monotonic() - started,
        "processReturnCodeAfterTermination": process.returncode, "error": error,
        "expectedSkillPath": expected, "archcanvasRows": rows, "exactExpectedMatches": len(exact), "archcanvasRowCount": len(rows),
        "discoveryErrors": [row for entry in entries for row in entry.get("errors", [])],
        "modelRequests": 0, "threadRequests": 0, "turnRequests": 0, "globalSkillWrites": False,
        "skillBodyLoadedIntoModelPrompt": False, "hostE2E": "not-tested",
        "limits": ["List/metadata parsing is not prompt injection, browser editing or host end-to-end certification.",
                   "Global Skill metadata may appear in the raw response; only the exact expected project Skill counts."]
    }
    artifacts = {"receipt.json": encode(receipt), "requests.json": encode(requests),
                 "transcript.json": encode(transcript), "stderr.txt": "\n".join(stderr) + "\n"}
    for name, text in artifacts.items():
        (args.output / name).write_text(text, encoding="utf-8")
    (args.output / "inventory.json").write_text(encode([{"path": name, "sha256": hashlib.sha256(text.encode()).hexdigest(), "bytes": len(text.encode())} for name, text in artifacts.items()]), encoding="utf-8")
    print(encode(receipt))
    return 0 if receipt["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
