// Independent literal geometry and frozen actual-CNN acceptance fixtures are
// retained beside their pre-fix receipts rather than generated by the product.
import '../../docs/evidence/m4-collapse-continuity-work/acceptance/collapse-continuity-independent.test.ts';
